apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: search
spec:
  replicas: 3
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: ccseyhan/search
        ports:
        - containerPort: 80
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD
        envFrom:
          - configMapRef:
              name: servers-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  type: NodePort
  selector:
    app: search
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002